//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BildirimDurum
    {
        public int Bildirim_ID { get; set; }
        public string Olay_Adi { get; set; }
        public string Sera_Adi { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Resim { get; set; }
        public string Baslangic_Saat { get; set; }
        public string Bitis_Saat { get; set; }
        public string Eski_Olay { get; set; }
        public string Yeni_Olay { get; set; }
    }
}
