//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisOrtam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisOrtam()
        {
            this.DisOrtamLog = new HashSet<DisOrtamLog>();
            this.DisOrtamSera = new HashSet<DisOrtamSera>();
        }
    
        public int DisOrtam_ID { get; set; }
        public string DisOrtam_Ad { get; set; }
        public bool DisOrtam_Aktif { get; set; }
        public System.DateTime DisOrtam_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisOrtamLog> DisOrtamLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisOrtamSera> DisOrtamSera { get; set; }
    }
}
