//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavaNemIsiLog
    {
        public int HavaNemIsiLog_ID { get; set; }
        public int HavaNemIsi_ID { get; set; }
        public string HavaNemIsiLog_IsiDeger { get; set; }
        public string HavaNemIsiLog_NemDeger { get; set; }
        public string HavaNemIsiLog_Akim { get; set; }
        public System.DateTime HavaNemIsiLog_Tarih { get; set; }
    
        public virtual HavaNemIsi HavaNemIsi { get; set; }
    }
}
