//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsikSiddet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IsikSiddet()
        {
            this.IsikSiddetLog = new HashSet<IsikSiddetLog>();
            this.IsikSiddetSera = new HashSet<IsikSiddetSera>();
        }
    
        public int IsikSiddet_ID { get; set; }
        public string IsikSiddet_Ad { get; set; }
        public bool IsikSiddet_Aktif { get; set; }
        public System.DateTime IsikSiddet_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsikSiddetLog> IsikSiddetLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsikSiddetSera> IsikSiddetSera { get; set; }
    }
}
