//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seralar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seralar()
        {
            this.DisOrtamSera = new HashSet<DisOrtamSera>();
            this.FanSera = new HashSet<FanSera>();
            this.HavaKaliteSera = new HashSet<HavaKaliteSera>();
            this.HavaNemIsiSera = new HashSet<HavaNemIsiSera>();
            this.IlacMotorTankSera = new HashSet<IlacMotorTankSera>();
            this.IsikSera = new HashSet<IsikSera>();
            this.IsikSiddetSera = new HashSet<IsikSiddetSera>();
            this.SeraUrun = new HashSet<SeraUrun>();
            this.SuMotorSera = new HashSet<SuMotorSera>();
            this.ToprakNemSera = new HashSet<ToprakNemSera>();
        }
    
        public int Sera_ID { get; set; }
        public int Sera_Kullanici_ID { get; set; }
        public string Sera_Ad { get; set; }
        public System.DateTime Sera_Tarih { get; set; }
        public bool Sera_Aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisOrtamSera> DisOrtamSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FanSera> FanSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaKaliteSera> HavaKaliteSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaNemIsiSera> HavaNemIsiSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlacMotorTankSera> IlacMotorTankSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsikSera> IsikSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsikSiddetSera> IsikSiddetSera { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeraUrun> SeraUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuMotorSera> SuMotorSera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToprakNemSera> ToprakNemSera { get; set; }
    }
}
