//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuMotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuMotor()
        {
            this.SuMotorLog = new HashSet<SuMotorLog>();
            this.SuMotorSera = new HashSet<SuMotorSera>();
        }
    
        public int SuMotor_ID { get; set; }
        public string SuMotor_Ad { get; set; }
        public bool SuMotor_Aktif { get; set; }
        public System.DateTime SuMotor_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuMotorLog> SuMotorLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuMotorSera> SuMotorSera { get; set; }
    }
}
