//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToprakNem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToprakNem()
        {
            this.ToprakNemLog = new HashSet<ToprakNemLog>();
            this.ToprakNemSera = new HashSet<ToprakNemSera>();
        }
    
        public int ToprakNem_ID { get; set; }
        public string ToprakNem_Ad { get; set; }
        public bool ToprakNem_Aktif { get; set; }
        public System.DateTime ToprakNem_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToprakNemLog> ToprakNemLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToprakNemSera> ToprakNemSera { get; set; }
    }
}
