//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavaKalite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HavaKalite()
        {
            this.HavaKaliteLog = new HashSet<HavaKaliteLog>();
            this.HavaKaliteSera = new HashSet<HavaKaliteSera>();
        }
    
        public int HavaKalite_ID { get; set; }
        public string HavaKalite_Ad { get; set; }
        public bool HavaKalite_Aktif { get; set; }
        public System.DateTime HavaKalite_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaKaliteLog> HavaKaliteLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaKaliteSera> HavaKaliteSera { get; set; }
    }
}
