//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlacMotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlacMotor()
        {
            this.IlacMotorLog = new HashSet<IlacMotorLog>();
            this.IlacMotorTankSera = new HashSet<IlacMotorTankSera>();
        }
    
        public int IlacMotor_ID { get; set; }
        public string IlacMotor_Ad { get; set; }
        public bool IlacMotor_Aktif { get; set; }
        public System.DateTime IlacMotor_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlacMotorLog> IlacMotorLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlacMotorTankSera> IlacMotorTankSera { get; set; }
    }
}
