//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlacMotorLog
    {
        public int IlacMotorLog_ID { get; set; }
        public int IlacMotor_ID { get; set; }
        public string IlacMotorLog_PwmDeger { get; set; }
        public string IlacMotorLog_MotorAkim { get; set; }
        public string IlacMotorLog_AkisDeger { get; set; }
        public System.DateTime IlacMotorLog_Tarih { get; set; }
    
        public virtual IlacMotor IlacMotor { get; set; }
    }
}
