//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeraUrun
    {
        public int SeraUrun_ID { get; set; }
        public int Sera_ID { get; set; }
        public int Urun_ID { get; set; }
        public System.DateTime Sera_EkimTarih { get; set; }
        public System.DateTime Sera_HasatTarih { get; set; }
        public string MaxSicaklik { get; set; }
        public string MinSicaklik { get; set; }
        public string MaxNem { get; set; }
        public string MinNem { get; set; }
        public string MaxIsik { get; set; }
        public string MinIsik { get; set; }
        public string MaxHava { get; set; }
        public string MinHava { get; set; }
        public string MaxToprakNem { get; set; }
        public string MinToprakNem { get; set; }
        public string HedefSicaklik { get; set; }
        public string HedefNem { get; set; }
        public string HedefIsik { get; set; }
        public string HedefHava { get; set; }
        public string SicaklikCumle1 { get; set; }
        public string SicaklikCumle2 { get; set; }
        public string NemCumle1 { get; set; }
        public string NemCumle2 { get; set; }
        public string HavaCumle1 { get; set; }
        public string HavaCumle2 { get; set; }
        public string IsikCumle1 { get; set; }
        public string IsikCumle2 { get; set; }
    
        public virtual Seralar Seralar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
