//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToprakNemLog
    {
        public int ToprakNemLog_ID { get; set; }
        public int ToprakNem_ID { get; set; }
        public string ToprakNemLog_Deger { get; set; }
        public string ToprakNemLog_Akim { get; set; }
        public System.DateTime ToprakNemLog_Tarih { get; set; }
    
        public virtual ToprakNem ToprakNem { get; set; }
    }
}
