//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisOrtamLog
    {
        public int DisOrtamLog_ID { get; set; }
        public int DisOrtam_ID { get; set; }
        public string DisOrtamLog_YagmurDeger { get; set; }
        public byte[] DisOrtamLog_YagmurAkim { get; set; }
        public string DisOrtamLog_SicaklikDeger { get; set; }
        public string DisOrtamLog_SicaklikAkim { get; set; }
        public string DisOrtamLog_NemDeger { get; set; }
        public string DisOrtamLog_NemAkim { get; set; }
        public string DisOrtam_RuzgarDeger { get; set; }
        public System.DateTime DisOrtamLog_Tarih { get; set; }
    
        public virtual DisOrtam DisOrtam { get; set; }
    }
}
