//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FanLog
    {
        public int FanLog_ID { get; set; }
        public int Fan_ID { get; set; }
        public string FanLog_PwmDeger { get; set; }
        public byte[] FanLog_FanAkim { get; set; }
        public string FanLog_IsıPwmDeger { get; set; }
        public string FanLog_IsiAkim { get; set; }
        public string FanLog_SicaklikDeger { get; set; }
        public string FanLog_SicaklikAkim { get; set; }
        public System.DateTime FanLog_Tarih { get; set; }
    
        public virtual Fan Fan { get; set; }
    }
}
