//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavaNemIsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HavaNemIsi()
        {
            this.HavaNemIsiLog = new HashSet<HavaNemIsiLog>();
            this.HavaNemIsiSera = new HashSet<HavaNemIsiSera>();
        }
    
        public int HavaNemIsi_ID { get; set; }
        public string HavaNemIsi_Ad { get; set; }
        public bool HavaNemIsi_Aktif { get; set; }
        public System.DateTime HavaNemIsi_Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaNemIsiLog> HavaNemIsiLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HavaNemIsiSera> HavaNemIsiSera { get; set; }
    }
}
