//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlacTank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlacTank()
        {
            this.IlacMotorTankSera = new HashSet<IlacMotorTankSera>();
        }
    
        public int IlacTank_ID { get; set; }
        public int Ilac_ID { get; set; }
        public string IlacTank_MaxMiktar { get; set; }
        public string IlacTank_AktifMiktar { get; set; }
        public System.DateTime IlacTank_Tarih { get; set; }
    
        public virtual Ilac Ilac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlacMotorTankSera> IlacMotorTankSera { get; set; }
    }
}
