//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlacMotorTankSera
    {
        public int IlacMotorTankSera_ID { get; set; }
        public int IlacMotor_ID { get; set; }
        public int IlacTank_ID { get; set; }
        public int Sera_ID { get; set; }
        public System.DateTime IlacMotorTankSera_Tarih { get; set; }
    
        public virtual IlacMotor IlacMotor { get; set; }
        public virtual IlacTank IlacTank { get; set; }
        public virtual Seralar Seralar { get; set; }
    }
}
