//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalanaWebApi.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToprakNemSera
    {
        public int ToprakNemSera_ID { get; set; }
        public int ToprakNem_ID { get; set; }
        public int Sera_ID { get; set; }
        public System.DateTime ToprakNemSera_Tarih { get; set; }
    
        public virtual Seralar Seralar { get; set; }
        public virtual ToprakNem ToprakNem { get; set; }
    }
}
